### PR TITLE
Some Relay improvements

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
See commit messages for more details.

### CODE REVIEW

**Comment by JulianKniephoff** [comment]
@LukasKalbertodt can you link your relay bug report here for future reference?

**Review by JulianKniephoff — CHANGES_REQUESTED** [review]
The ESLint configuration still references `query-types`. :thinking:

**Comment by LukasKalbertodt** [comment]
> @LukasKalbertodt can you link your relay bug report here for future reference?

https://github.com/facebook/relay/issues/3782

**Comment by LukasKalbertodt** [comment]
Merging since I solved the only comment.

**Pull request merged**
