### PR TITLE
Add remaining dashboard items to user menu

### LINKED ISSUE #751: Rethink what items to include in the user menu
Currently we have "my content", "Upload video" (and always "logout", but thats not part of this discussion -- it stays there of course). "My content" links to the management dashboard. #727 will add "my page". It's unclear why "upload video" is linked there, but not "record video" (with studio). Or "my videos". So we should think about this again and find a more consistent solution.

### PR DESCRIPTION
**Pull request by owi92**
This adds a link to the "My videos" page and an external link to "Record video" (with studio) to the user menu.

This took longer than I expected because I durdled around with making the `externalLink` component reusable as `MenuItem` for the user menu. Since we don't plan to add any more external links to that menu, that might seem kinda pointless. But I think it makes the menu and `menuItem` at least a little cleaner without having to pull out the shared css styles.

closes #751

### CODE REVIEW

**Review by LukasKalbertodt — APPROVED** [review]
Yep, that's better! Code looks good.

---

When testing this out, I got the idea of indenting some points like so:

image

(never mind the missing "record video", couldn't get padding to work as easily :D)

I also changed the label "My content" to "Manage", as this leads to the management dashboard. One might also try to find a better icon for it (maybe `sliders` from feather icons? Or activity, box, settings?)

What do you think?

**Comment by LukasKalbertodt** [comment]
Oh and I suppose there should be a "my page" item on the management dashboard then? :thinking: For consistency?

**Comment by owi92** [comment]
> there should be a "my page" item on the management dashboard then?

Yes I agree. Not a 100% sure about the look of the indentation but also not really opposed. It does make sense since they are subitems of the "Manage" page 🤷

**Comment by LukasKalbertodt** [comment]
Feel free to experiment with the look. Indentation is simply the first thing I could think of. I think it would make sense to somehow indicate the "subitem" status. Or at least group items? Mhh

**Comment by owi92** [comment]
Regarding the icon for "manage", I still think the folders icon works best.
I find that sliders, activity and settings all convey different things than this actually does. And even though we use the `HiOutlineTemplate` in navigation for this page, it looks a little off in this context.
I made some screenshots for comparison.
Bildschirmfoto 2023-04-19 um 11 10 03 Bildschirmfoto 2023-04-19 um 11 10 25 Bildschirmfoto 2023-04-19 um 11 10 47 Bildschirmfoto 2023-04-19 um 11 11 14 Bildschirmfoto 2023-04-19 um 11 13 10 Bildschirmfoto 2023-04-19 um 11 18 37

**Comment by owi92** [comment]
Oh I just missed your comments. I'll amend the commit.

**Comment by owi92** [comment]
Soo, since we still don't have definite decision on the icon, maybe stick with "folder" for now? Though I wouldn't mind using the "slider" instead.

**Review by LukasKalbertodt — APPROVED** [review]
> Soo, since we still don't have a definite decision on the icon, maybe stick with "folder" for now? Though I wouldn't mind using the "slider" instead.

Sounds good to me!

**Pull request merged**
